"""Updated TIMESTAMP again AGAIN This time for real Maybe this time

Revision ID: 817179005d54
Revises: 80b1f86d8bff
Create Date: 2025-05-05 11:45:17.636741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '817179005d54'
down_revision: Union[str, None] = '80b1f86d8bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_review', sa.Column('made_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('c_review', 'created_at')
    op.add_column('character', sa.Column('made_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('character', 'created_at')
    op.add_column('f_review', sa.Column('made_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('f_review', 'created_at')
    op.add_column('user', sa.Column('made_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'made_at')
    op.add_column('f_review', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('f_review', 'made_at')
    op.add_column('character', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('character', 'made_at')
    op.add_column('c_review', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('c_review', 'made_at')
    # ### end Alembic commands ###
