"""Fixed BattleVotes

Revision ID: 98ccf8b5e0fb
Revises: 817179005d54
Create Date: 2025-05-12 10:23:12.732414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ccf8b5e0fb'
down_revision: Union[str, None] = '817179005d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('battle', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('battle', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battle', 'end_date')
    op.drop_column('battle', 'start_date')
    op.drop_table('battle_votes')
    # ### end Alembic commands ###
