"""Changing winnerid to be nullable=True

Revision ID: c2a3bc0e7799
Revises: 98ccf8b5e0fb
Create Date: 2025-05-12 11:48:37.198761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a3bc0e7799'
down_revision: Union[str, None] = '98ccf8b5e0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battle', 'winner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battle', 'winner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
